name: Deploy via FTP

on:
  push:
    branches:
      - '**'

jobs:
  ftp-deploy:
    name: Upload site to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.eldrmedia.com
          username: development@eldrmedia.com
          password: Welder2699!
          local-dir: /  # change to your build output folder
          server-dir: /  # change to your server directory
          exclude: |
            **/.git*
            **/.github*
            **/src/**
            **/node_modules/**
            **/package*.json
            **/README.md
            package.json
