name: Deploy via FTP

on:
  push:
    branches:
      - '**'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
          server: ftp.eldrmedia.com
          username: development@eldrmedia.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # change to your build output folder
          server-dir: ./  # change to your server directory
          exclude: |
            **/.git*
            **/.github*
            **/src/**
            **/node_modules/**
            **/package*.json
            **/README.md
            package.json
